"""Fuzzing harness generator for QEMU peripheral models.

Generates AFL/libFuzzer C harnesses that exercise QEMU MemoryRegionOps
callbacks with random register offsets and values to find crashes,
hangs, and undefined behavior.
"""

from __future__ import annotations

from pathlib import Path

from autoemu.models.peripheral import Peripheral
from autoemu.models.register import AccessType
from autoemu.modeling_utils import snake_case as _snake


def generate_fuzz_harness(
    peripheral: Peripheral,
    output_dir: str | Path,
) -> list[str]:
    """Generate AFL/libFuzzer harnesses for the peripheral model.

    Returns list of generated file paths.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    files: list[str] = []

    # 1. Register fuzz harness
    reg_path = output_dir / f"fuzz_{_snake(peripheral.name)}_regs.c"
    reg_path.write_text(_generate_register_fuzzer(peripheral), encoding="utf-8")
    files.append(str(reg_path))

    # 2. State transition fuzzer
    state_path = output_dir / f"fuzz_{_snake(peripheral.name)}_states.c"
    state_path.write_text(_generate_state_fuzzer(peripheral), encoding="utf-8")
    files.append(str(state_path))

    return files


def _generate_register_fuzzer(peripheral: Peripheral) -> str:
    """Generate a libFuzzer harness for register read/write operations.

    The harness reads fuzzer input in 6-byte chunks:
      - 2 bytes: register offset
      - 4 bytes: write value
    For each chunk it calls the peripheral write then read handler.
    """
    name = peripheral.name
    snake = _snake(name)

    max_offset = 0
    if peripheral.register_block.registers:
        max_offset = max(r.offset for r in peripheral.register_block.registers) + 4

    lines = [
        "/*",
        f" * libFuzzer harness for STM32 {name} register operations",
        " *",
        " * Auto-generated by AutoEmu",
        " *",
        f" * Build: clang -g -fsanitize=fuzzer,address -o fuzz_{snake}_regs \\",
        f" *        fuzz_{snake}_regs.c stm32_{snake}.c -I<qemu-includes>",
        " */",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "#include <string.h>",
        "",
        "/* Forward declarations for peripheral ops */",
        f"extern uint64_t stm32_{snake}_read(void *opaque, uint64_t offset, unsigned size);",
        f"extern void stm32_{snake}_write(void *opaque, uint64_t offset, uint64_t value, unsigned size);",
        "",
        "/* Minimal stub state — in a real build link against the QEMU object */",
        "static uint8_t state_blob[4096];",
        "",
        "/* Known register offsets for targeted fuzzing */",
        "static const uint16_t known_offsets[] = {",
    ]

    for reg in peripheral.register_block.registers:
        lines.append(f"    0x{reg.offset:04X}, /* {reg.name} */")

    lines.extend([
        "};",
        "",
        f"#define MAX_OFFSET  0x{max_offset:04X}",
        "#define CHUNK_SIZE  6  /* 2 bytes offset + 4 bytes value */",
        "",
        "int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)",
        "{",
        "    void *opaque = (void *)state_blob;",
        "    size_t pos = 0;",
        "",
        "    /* Reset state between runs */",
        "    memset(state_blob, 0, sizeof(state_blob));",
        "",
        "    while (pos + CHUNK_SIZE <= size) {",
        "        /* Extract offset (2 bytes, little-endian) and value (4 bytes, LE) */",
        "        uint16_t raw_offset = (uint16_t)data[pos] | ((uint16_t)data[pos + 1] << 8);",
        "        uint32_t value = (uint32_t)data[pos + 2]",
        "                       | ((uint32_t)data[pos + 3] << 8)",
        "                       | ((uint32_t)data[pos + 4] << 16)",
        "                       | ((uint32_t)data[pos + 5] << 24);",
        "",
        "        /* Align offset to 4-byte boundary, allow out-of-range for coverage */",
        "        uint64_t offset = (raw_offset & 0xFFFC);",
        "",
        "        /* Write then read — exercises both MemoryRegionOps callbacks */",
        f"        stm32_{snake}_write(opaque, offset, value, 4);",
        f"        (void)stm32_{snake}_read(opaque, offset, 4);",
        "",
        "        pos += CHUNK_SIZE;",
        "    }",
        "",
        "    return 0;",
        "}",
    ])

    return "\n".join(lines)


def _generate_state_fuzzer(peripheral: Peripheral) -> str:
    """Generate a libFuzzer harness for state machine transitions.

    Sends sequences of register writes designed to race through state
    machine transitions. Uses fuzzer input to select register/value pairs
    and interposes IRQ checks between writes.
    """
    name = peripheral.name
    snake = _snake(name)

    # Collect registers involved in state transitions
    transition_regs: list[tuple[str, int]] = []
    trigger_reg_names: set[str] = set()
    for sm in peripheral.state_machines:
        for t in sm.transitions:
            if t.trigger.startswith("reg_write:"):
                trigger_reg_names.add(t.trigger.split(":", 1)[1])

    for reg in peripheral.register_block.registers:
        if reg.name in trigger_reg_names or reg.access in (AccessType.RW, AccessType.WO):
            transition_regs.append((reg.name, reg.offset))

    if not transition_regs:
        # Fall back to all writable registers
        transition_regs = [
            (r.name, r.offset)
            for r in peripheral.register_block.registers
            if r.access != AccessType.RO
        ]

    n_regs = len(transition_regs) if transition_regs else 1

    lines = [
        "/*",
        f" * libFuzzer harness for STM32 {name} state transitions",
        " *",
        " * Auto-generated by AutoEmu",
        " *",
        f" * Build: clang -g -fsanitize=fuzzer,address -o fuzz_{snake}_states \\",
        f" *        fuzz_{snake}_states.c stm32_{snake}.c -I<qemu-includes>",
        " */",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "#include <string.h>",
        "",
        f"extern uint64_t stm32_{snake}_read(void *opaque, uint64_t offset, unsigned size);",
        f"extern void stm32_{snake}_write(void *opaque, uint64_t offset, uint64_t value, unsigned size);",
        "",
        "static uint8_t state_blob[4096];",
        "",
        "/* Registers involved in state transitions */",
        "static const struct {",
        "    const char *name;",
        "    uint16_t offset;",
        "} transition_regs[] = {",
    ]

    for rname, roffset in transition_regs:
        lines.append(f"    {{ \"{rname}\", 0x{roffset:04X} }},")

    lines.extend([
        "};",
        "",
        f"#define N_TRANSITION_REGS  {n_regs}",
        "#define CHUNK_SIZE  5  /* 1 byte reg index + 4 bytes value */",
        "",
        "int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)",
        "{",
        "    void *opaque = (void *)state_blob;",
        "    size_t pos = 0;",
        "",
        "    memset(state_blob, 0, sizeof(state_blob));",
        "",
        "    while (pos + CHUNK_SIZE <= size) {",
        "        /* Select a transition register using first byte */",
        "        uint8_t reg_idx = data[pos] % N_TRANSITION_REGS;",
        "        uint32_t value = (uint32_t)data[pos + 1]",
        "                       | ((uint32_t)data[pos + 2] << 8)",
        "                       | ((uint32_t)data[pos + 3] << 16)",
        "                       | ((uint32_t)data[pos + 4] << 24);",
        "",
        "        uint16_t offset = transition_regs[reg_idx].offset;",
        "",
        "        /* Write to drive state transition */",
        f"        stm32_{snake}_write(opaque, offset, value, 4);",
        "",
        "        /* Read back — triggers IRQ update path */",
        f"        (void)stm32_{snake}_read(opaque, offset, 4);",
        "",
        "        pos += CHUNK_SIZE;",
        "    }",
        "",
        "    return 0;",
        "}",
    ])

    return "\n".join(lines)
