"""QEMU peripheral model C code generator.

Generates QEMU-compatible C source and header files from peripheral models,
following QEMU's Object model, MemoryRegionOps, and IRQ conventions.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from autoemu.models.register import AccessType, BitField, Register, RegisterBlock
from autoemu.models.peripheral import Peripheral
from autoemu.models.state_machine import StateMachine
from autoemu.models.interrupt import InterruptModel


def _snake(name: str) -> str:
    """Convert name to snake_case."""
    result = []
    for i, c in enumerate(name):
        if c.isupper() and i > 0 and not name[i - 1].isupper():
            result.append("_")
        result.append(c.lower())
    return "".join(result).replace("__", "_")


def _upper(name: str) -> str:
    return _snake(name).upper()


def _generate_header(peripheral: Peripheral) -> str:
    """Generate the QEMU peripheral header file."""
    name = peripheral.name
    snake = _snake(name)
    upper = _upper(name)
    type_name = f"STM32{upper}State"

    lines = [
        f"/*",
        f" * STM32 {name} peripheral emulation",
        f" *",
        f" * Auto-generated by AutoEmu",
        f" */",
        f"",
        f"#ifndef HW_STM32_{upper}_H",
        f"#define HW_STM32_{upper}_H",
        f"",
        f"#include \"hw/sysbus.h\"",
        f"#include \"qom/object.h\"",
        f"",
        f"#define TYPE_STM32_{upper} \"stm32-{snake}\"",
        f"OBJECT_DECLARE_SIMPLE_TYPE({type_name}, STM32_{upper})",
        f"",
    ]

    # Register offset defines
    lines.append(f"/* Register offsets */")
    for reg in peripheral.register_block.registers:
        lines.append(f"#define {upper}_{reg.name}_OFFSET  0x{reg.offset:03X}")
    lines.append("")

    # Bit field defines
    for reg in peripheral.register_block.registers:
        if reg.fields:
            lines.append(f"/* {reg.name} bit fields */")
            for f in reg.fields:
                lines.append(
                    f"#define {upper}_{reg.name}_{f.name}_Pos  {f.bit_offset}"
                )
                lines.append(
                    f"#define {upper}_{reg.name}_{f.name}_Msk  "
                    f"(0x{((1 << f.bit_width) - 1):X}U << {f.bit_offset})"
                )
            lines.append("")

    # State struct
    lines.append(f"struct {type_name} {{")
    lines.append(f"    SysBusDevice parent_obj;")
    lines.append(f"")
    lines.append(f"    MemoryRegion mmio;")
    lines.append(f"")

    # IRQ outputs
    if peripheral.interrupt_model and peripheral.interrupt_model.lines:
        n_irq = len(peripheral.interrupt_model.lines)
        lines.append(f"    qemu_irq irq[{n_irq}];")
        lines.append(f"")

    # Register storage
    lines.append(f"    /* Registers */")
    for reg in peripheral.register_block.registers:
        lines.append(f"    uint32_t {reg.name.lower()};")
    lines.append(f"")

    # State machine state
    for sm in peripheral.state_machines:
        lines.append(f"    /* {sm.name} state machine */")
        lines.append(f"    uint32_t {_snake(sm.name)}_state;")
    lines.append(f"")

    lines.append(f"}};")
    lines.append(f"")
    lines.append(f"#endif /* HW_STM32_{upper}_H */")

    return "\n".join(lines)


def _generate_reg_read(peripheral: Peripheral) -> str:
    """Generate the register read function body."""
    upper = _upper(peripheral.name)
    snake = _snake(peripheral.name)
    lines = []

    lines.append(f"    switch (offset) {{")
    for reg in peripheral.register_block.registers:
        lines.append(f"    case {upper}_{reg.name}_OFFSET:")

        # Handle read-clear and write-only fields
        has_special_read = any(
            f.access in (AccessType.RC_W1, AccessType.RC_W0, AccessType.WO, AccessType.RS)
            for f in reg.fields
        )

        if has_special_read:
            lines.append(f"    {{")
            lines.append(f"        uint32_t val = s->{reg.name.lower()};")
            for f in reg.fields:
                if f.access in (AccessType.RC_W1, AccessType.RC_W0):
                    lines.append(
                        f"        s->{reg.name.lower()} &= ~{upper}_{reg.name}_{f.name}_Msk;"
                    )
                elif f.access == AccessType.WO:
                    lines.append(
                        f"        val &= ~{upper}_{reg.name}_{f.name}_Msk;"
                    )
            lines.append(f"        stm32_{snake}_update_irq(s);")
            lines.append(f"        return val;")
            lines.append(f"    }}")
        elif reg.access == AccessType.WO:
            lines.append(f"        return 0;")
        else:
            lines.append(f"        return s->{reg.name.lower()};")

    lines.append(f"    default:")
    lines.append(f"        qemu_log_mask(LOG_GUEST_ERROR,")
    lines.append(f"            \"stm32_{snake}: bad read offset 0x%\" HWADDR_PRIx \"\\n\",")
    lines.append(f"            offset);")
    lines.append(f"        return 0;")
    lines.append(f"    }}")

    return "\n".join(lines)


def _generate_reg_write(peripheral: Peripheral) -> str:
    """Generate the register write function body."""
    upper = _upper(peripheral.name)
    snake = _snake(peripheral.name)
    lines = []

    lines.append(f"    switch (offset) {{")
    for reg in peripheral.register_block.registers:
        if reg.access == AccessType.RO:
            lines.append(f"    case {upper}_{reg.name}_OFFSET:")
            lines.append(f"        /* Read-only register, write ignored */")
            lines.append(f"        break;")
            continue

        lines.append(f"    case {upper}_{reg.name}_OFFSET:")

        has_special_write = any(
            f.access in (AccessType.W1C, AccessType.W1S, AccessType.W0C, AccessType.RO, AccessType.RSVD)
            for f in reg.fields
        )

        if has_special_write:
            lines.append(f"    {{")
            lines.append(f"        uint32_t old = s->{reg.name.lower()};")

            rw_mask = 0
            w1c_mask = 0
            w1s_mask = 0
            ro_mask = 0

            for f in reg.fields:
                match f.access:
                    case AccessType.W1C:
                        w1c_mask |= f.mask
                    case AccessType.W1S:
                        w1s_mask |= f.mask
                    case AccessType.RO | AccessType.RSVD:
                        ro_mask |= f.mask
                    case _:
                        rw_mask |= f.mask

            if ro_mask:
                lines.append(f"        /* Preserve read-only bits */")
                lines.append(f"        uint32_t new_val = old & 0x{ro_mask:08X}U;")
            else:
                lines.append(f"        uint32_t new_val = 0;")

            if rw_mask:
                lines.append(f"        new_val |= value & 0x{rw_mask:08X}U;")

            if w1c_mask:
                lines.append(f"        /* Write-1-to-clear bits */")
                lines.append(f"        new_val |= old & ~(value & 0x{w1c_mask:08X}U) & 0x{w1c_mask:08X}U;")

            if w1s_mask:
                lines.append(f"        /* Write-1-to-set bits */")
                lines.append(f"        new_val |= (old | value) & 0x{w1s_mask:08X}U;")

            lines.append(f"        s->{reg.name.lower()} = new_val;")
            lines.append(f"        stm32_{snake}_update_irq(s);")
            lines.append(f"        break;")
            lines.append(f"    }}")
        else:
            lines.append(f"        s->{reg.name.lower()} = value;")
            lines.append(f"        stm32_{snake}_update_irq(s);")
            lines.append(f"        break;")

    lines.append(f"    default:")
    lines.append(f"        qemu_log_mask(LOG_GUEST_ERROR,")
    lines.append(f"            \"stm32_{snake}: bad write offset 0x%\" HWADDR_PRIx \"\\n\",")
    lines.append(f"            offset);")
    lines.append(f"        break;")
    lines.append(f"    }}")

    return "\n".join(lines)


def _generate_source(peripheral: Peripheral) -> str:
    """Generate the QEMU peripheral C source file."""
    name = peripheral.name
    snake = _snake(name)
    upper = _upper(name)
    type_name = f"STM32{upper}State"

    lines = [
        f"/*",
        f" * STM32 {name} peripheral emulation",
        f" *",
        f" * Auto-generated by AutoEmu",
        f" */",
        f"",
        f"#include \"qemu/osdep.h\"",
        f"#include \"hw/stm32_{snake}.h\"",
        f"#include \"qemu/log.h\"",
        f"#include \"migration/vmstate.h\"",
        f"",
    ]

    # IRQ update function
    n_irq = 0
    if peripheral.interrupt_model:
        n_irq = len(peripheral.interrupt_model.lines)

    lines.append(f"static void stm32_{snake}_update_irq({type_name} *s)")
    lines.append(f"{{")
    if peripheral.interrupt_model and peripheral.interrupt_model.lines:
        for i, irq_line in enumerate(peripheral.interrupt_model.lines):
            if irq_line.flags:
                conditions = []
                for flag in irq_line.flags:
                    sr = flag.register_name.lower()
                    er = flag.enable_register.lower()
                    conditions.append(
                        f"(s->{sr} & (1U << {flag.bit_offset})) && "
                        f"(s->{er} & (1U << {flag.enable_bit_offset}))"
                    )
                if conditions:
                    cond_str = " ||\n            ".join(conditions)
                    lines.append(f"    int level_{i} = ({cond_str}) ? 1 : 0;")
                    lines.append(f"    qemu_set_irq(s->irq[{i}], level_{i});")
                else:
                    lines.append(f"    qemu_set_irq(s->irq[{i}], 0);")
    lines.append(f"}}")
    lines.append(f"")

    # Read function
    lines.append(f"static uint64_t stm32_{snake}_read(void *opaque,")
    lines.append(f"    hwaddr offset, unsigned size)")
    lines.append(f"{{")
    lines.append(f"    {type_name} *s = STM32_{upper}(opaque);")
    lines.append(f"")
    lines.append(_generate_reg_read(peripheral))
    lines.append(f"}}")
    lines.append(f"")

    # Write function
    lines.append(f"static void stm32_{snake}_write(void *opaque,")
    lines.append(f"    hwaddr offset, uint64_t value, unsigned size)")
    lines.append(f"{{")
    lines.append(f"    {type_name} *s = STM32_{upper}(opaque);")
    lines.append(f"")
    lines.append(_generate_reg_write(peripheral))
    lines.append(f"}}")
    lines.append(f"")

    # MemoryRegionOps
    lines.append(f"static const MemoryRegionOps stm32_{snake}_ops = {{")
    lines.append(f"    .read = stm32_{snake}_read,")
    lines.append(f"    .write = stm32_{snake}_write,")
    lines.append(f"    .endianness = DEVICE_LITTLE_ENDIAN,")
    lines.append(f"    .impl.min_access_size = 4,")
    lines.append(f"    .impl.max_access_size = 4,")
    lines.append(f"}};")
    lines.append(f"")

    # Reset function
    lines.append(f"static void stm32_{snake}_reset(DeviceState *dev)")
    lines.append(f"{{")
    lines.append(f"    {type_name} *s = STM32_{upper}(dev);")
    lines.append(f"")
    for reg in peripheral.register_block.registers:
        lines.append(f"    s->{reg.name.lower()} = 0x{reg.reset_value:08X}U;")
    if peripheral.state_machines:
        for sm in peripheral.state_machines:
            lines.append(f"    s->{_snake(sm.name)}_state = 0;")
    lines.append(f"")
    lines.append(f"    stm32_{snake}_update_irq(s);")
    lines.append(f"}}")
    lines.append(f"")

    # Init function
    lines.append(f"static void stm32_{snake}_init(Object *obj)")
    lines.append(f"{{")
    lines.append(f"    {type_name} *s = STM32_{upper}(obj);")
    lines.append(f"    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);")
    lines.append(f"")
    lines.append(f"    memory_region_init_io(&s->mmio, obj, &stm32_{snake}_ops, s,")
    addr_size = peripheral.address_size or (
        max((r.offset for r in peripheral.register_block.registers), default=0) + 4
    )
    lines.append(f"        TYPE_STM32_{upper}, 0x{addr_size:X});")
    lines.append(f"    sysbus_init_mmio(sbd, &s->mmio);")
    lines.append(f"")
    if n_irq:
        for i in range(n_irq):
            lines.append(f"    sysbus_init_irq(sbd, &s->irq[{i}]);")
    lines.append(f"}}")
    lines.append(f"")

    # VMState for migration
    lines.append(f"static const VMStateDescription vmstate_stm32_{snake} = {{")
    lines.append(f"    .name = TYPE_STM32_{upper},")
    lines.append(f"    .version_id = 1,")
    lines.append(f"    .minimum_version_id = 1,")
    lines.append(f"    .fields = (VMStateField[]) {{")
    for reg in peripheral.register_block.registers:
        lines.append(
            f"        VMSTATE_UINT32(s->{reg.name.lower()}, {type_name}),"
        )
    lines.append(f"        VMSTATE_END_OF_LIST()")
    lines.append(f"    }},")
    lines.append(f"}};")
    lines.append(f"")

    # Class init
    lines.append(f"static void stm32_{snake}_class_init(ObjectClass *klass, void *data)")
    lines.append(f"{{")
    lines.append(f"    DeviceClass *dc = DEVICE_CLASS(klass);")
    lines.append(f"")
    lines.append(f"    dc->reset = stm32_{snake}_reset;")
    lines.append(f"    dc->vmsd = &vmstate_stm32_{snake};")
    lines.append(f"}}")
    lines.append(f"")

    # TypeInfo
    lines.append(f"static const TypeInfo stm32_{snake}_info = {{")
    lines.append(f"    .name          = TYPE_STM32_{upper},")
    lines.append(f"    .parent        = TYPE_SYS_BUS_DEVICE,")
    lines.append(f"    .instance_size = sizeof({type_name}),")
    lines.append(f"    .instance_init = stm32_{snake}_init,")
    lines.append(f"    .class_init    = stm32_{snake}_class_init,")
    lines.append(f"}};")
    lines.append(f"")

    # Type registration
    lines.append(f"static void stm32_{snake}_register_types(void)")
    lines.append(f"{{")
    lines.append(f"    type_register_static(&stm32_{snake}_info);")
    lines.append(f"}}")
    lines.append(f"")
    lines.append(f"type_init(stm32_{snake}_register_types)")

    return "\n".join(lines)


def generate_peripheral_code(
    peripheral: Peripheral,
    output_dir: str | Path,
) -> list[str]:
    """Generate QEMU peripheral model files.

    Returns list of generated file paths.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    snake = _snake(peripheral.name)
    files: list[str] = []

    # Header
    header_path = output_dir / f"stm32_{snake}.h"
    header_path.write_text(_generate_header(peripheral), encoding="utf-8")
    files.append(str(header_path))

    # Source
    source_path = output_dir / f"stm32_{snake}.c"
    source_path.write_text(_generate_source(peripheral), encoding="utf-8")
    files.append(str(source_path))

    # Model JSON (for reference)
    json_path = output_dir / f"stm32_{snake}_model.json"
    json_path.write_text(peripheral.model_dump_json(indent=2), encoding="utf-8")
    files.append(str(json_path))

    return files
