"""QEMU peripheral model C code generator.

Generates latest-upstream-QEMU compatible C source and header files from peripheral
models, following QEMU's Object model, MemoryRegionOps, and IRQ conventions.

Target QEMU version: latest upstream QEMU
  - Uses device_class_set_legacy_reset() instead of legacy dc->reset assignment
  - Meson build system integration
  - QTest generation for in-tree validation
"""

from pathlib import Path

from autoemu.models.register import AccessType
from autoemu.models.peripheral import Peripheral
from autoemu.modeling_utils import snake_case as _snake, upper_case as _upper, normalize_name

QEMU_TARGET_VERSION = "latest upstream QEMU"


def _device_prefix(peripheral: Peripheral) -> str:
    """Derive a C-safe device prefix from the peripheral's mcu_family.

    Returns e.g. ``"stm32"`` for STM32F4, ``"hisilicon"`` for HIKEY960,
    ``"generic"`` when unknown.
    """
    family = (peripheral.mcu_family or "").strip()
    if not family:
        return "autoemu"
    return normalize_name(family)


def _generate_header(peripheral: Peripheral) -> str:
    """Generate the QEMU peripheral header file."""
    name = peripheral.name
    snake = _snake(name)
    upper = _upper(name)
    pfx = _device_prefix(peripheral)
    pfx_upper = pfx.upper()
    type_name = f"{pfx_upper}{upper}State"

    lines = [
        "/*",
        f" * {pfx_upper} {name} peripheral emulation",
        " *",
        f" * Auto-generated by AutoEmu (target: QEMU {QEMU_TARGET_VERSION})",
        " */",
        "",
        f"#ifndef HW_{pfx_upper}_{upper}_H",
        f"#define HW_{pfx_upper}_{upper}_H",
        "",
        "#include \"hw/sysbus.h\"",
        "#include \"qom/object.h\"",
        "",
        f"#define TYPE_{pfx_upper}_{upper} \"{pfx}-{snake}\"",
        f"OBJECT_DECLARE_SIMPLE_TYPE({type_name}, {pfx_upper}_{upper})",
        "",
    ]

    # Register offset defines
    lines.append("/* Register offsets */")
    for reg in peripheral.register_block.registers:
        lines.append(f"#define {upper}_{reg.name}_OFFSET  0x{reg.offset:03X}")
    lines.append("")

    # Bit field defines
    for reg in peripheral.register_block.registers:
        if reg.fields:
            lines.append(f"/* {reg.name} bit fields */")
            for f in reg.fields:
                lines.append(
                    f"#define {upper}_{reg.name}_{f.name}_Pos  {f.bit_offset}"
                )
                lines.append(
                    f"#define {upper}_{reg.name}_{f.name}_Msk  "
                    f"(0x{((1 << f.bit_width) - 1):X}U << {f.bit_offset})"
                )
            lines.append("")

    # State struct
    lines.append(f"struct {type_name} {{")
    lines.append("    SysBusDevice parent_obj;")
    lines.append("")
    lines.append("    MemoryRegion mmio;")
    lines.append("")

    # IRQ outputs
    if peripheral.interrupt_model and peripheral.interrupt_model.lines:
        n_irq = len(peripheral.interrupt_model.lines)
        lines.append(f"    qemu_irq irq[{n_irq}];")
        lines.append("")

    # Register storage
    lines.append("    /* Registers */")
    for reg in peripheral.register_block.registers:
        lines.append(f"    uint32_t {reg.name.lower()};")
    lines.append("")

    # State machine state
    for sm in peripheral.state_machines:
        lines.append(f"    /* {sm.name} state machine */")
        lines.append(f"    uint32_t {_snake(sm.name)}_state;")
    lines.append("")

    lines.append("};")
    lines.append("")
    lines.append(f"#endif /* HW_{pfx_upper}_{upper}_H */")

    return "\n".join(lines)


def _generate_reg_read(peripheral: Peripheral, pfx: str) -> str:
    """Generate the register read function body."""
    upper = _upper(peripheral.name)
    snake = _snake(peripheral.name)
    lines = []

    lines.append("    switch (offset) {")
    for reg in peripheral.register_block.registers:
        lines.append(f"    case {upper}_{reg.name}_OFFSET:")

        has_special_read = any(
            f.access in (AccessType.RC_W1, AccessType.RC_W0, AccessType.WO, AccessType.RS)
            for f in reg.fields
        )

        if has_special_read:
            lines.append("    {")
            lines.append(f"        uint32_t val = s->{reg.name.lower()};")
            for f in reg.fields:
                if f.access in (AccessType.RC_W1, AccessType.RC_W0):
                    lines.append(f"        s->{reg.name.lower()} &= ~{upper}_{reg.name}_{f.name}_Msk;")
                elif f.access == AccessType.WO:
                    lines.append(f"        val &= ~{upper}_{reg.name}_{f.name}_Msk;")
            lines.append(f"        {pfx}_{snake}_update_irq(s);")
            lines.append("        return val;")
            lines.append("    }")
        elif reg.access == AccessType.WO:
            lines.append("        return 0;")
        else:
            lines.append(f"        return s->{reg.name.lower()};")

    lines.append("    default:")
    lines.append("        qemu_log_mask(LOG_GUEST_ERROR,")
    lines.append(f"            \"{pfx}_{snake}: bad read offset 0x%\" HWADDR_PRIx \"\\n\",")
    lines.append("            offset);")
    lines.append("        return 0;")
    lines.append("    }")

    return "\n".join(lines)


def _generate_reg_write(peripheral: Peripheral, pfx: str) -> str:
    """Generate the register write function body."""
    upper = _upper(peripheral.name)
    snake = _snake(peripheral.name)
    lines = []

    lines.append("    switch (offset) {")
    for reg in peripheral.register_block.registers:
        if reg.access == AccessType.RO:
            lines.append(f"    case {upper}_{reg.name}_OFFSET:")
            lines.append("        /* Read-only register, write ignored */")
            lines.append("        break;")
            continue

        lines.append(f"    case {upper}_{reg.name}_OFFSET:")

        has_special_write = any(
            f.access in (AccessType.W1C, AccessType.W1S, AccessType.W0C, AccessType.RO, AccessType.RSVD)
            for f in reg.fields
        )

        if has_special_write:
            lines.append("    {")
            lines.append(f"        uint32_t old = s->{reg.name.lower()};")

            rw_mask = 0
            w1c_mask = 0
            w1s_mask = 0
            ro_mask = 0

            for f in reg.fields:
                match f.access:
                    case AccessType.W1C:
                        w1c_mask |= f.mask
                    case AccessType.W1S:
                        w1s_mask |= f.mask
                    case AccessType.RO | AccessType.RSVD:
                        ro_mask |= f.mask
                    case _:
                        rw_mask |= f.mask

            lines.append("        uint32_t new_val = old;")

            if rw_mask:
                lines.append("        /* Read-write bits */")
                lines.append(f"        new_val = (new_val & ~0x{rw_mask:08X}U) | (value & 0x{rw_mask:08X}U);")

            if w1c_mask:
                lines.append("        /* Write-1-to-clear bits */")
                lines.append(f"        new_val &= ~(value & 0x{w1c_mask:08X}U);")

            if w1s_mask:
                lines.append("        /* Write-1-to-set bits */")
                lines.append(f"        new_val |= (value & 0x{w1s_mask:08X}U);")

            if ro_mask:
                lines.append("        /* Preserve read-only bits */")
                lines.append(f"        new_val = (new_val & ~0x{ro_mask:08X}U) | (old & 0x{ro_mask:08X}U);")

            lines.append(f"        s->{reg.name.lower()} = new_val;")
            lines.append(f"        {pfx}_{snake}_update_irq(s);")
            lines.append("        break;")
            lines.append("    }")
        else:
            lines.append(f"        s->{reg.name.lower()} = value;")
            lines.append(f"        {pfx}_{snake}_update_irq(s);")
            lines.append("        break;")

    lines.append("    default:")
    lines.append("        qemu_log_mask(LOG_GUEST_ERROR,")
    lines.append(f"            \"{pfx}_{snake}: bad write offset 0x%\" HWADDR_PRIx \"\\n\",")
    lines.append("            offset);")
    lines.append("        break;")
    lines.append("    }")

    return "\n".join(lines)


def _generate_source(peripheral: Peripheral) -> str:
    """Generate the QEMU peripheral C source file."""
    name = peripheral.name
    snake = _snake(name)
    upper = _upper(name)
    pfx = _device_prefix(peripheral)
    pfx_upper = pfx.upper()
    type_name = f"{pfx_upper}{upper}State"

    lines = [
        "/*",
        f" * {pfx_upper} {name} peripheral emulation",
        " *",
        f" * Auto-generated by AutoEmu (target: QEMU {QEMU_TARGET_VERSION})",
        " */",
        "",
        "#include \"qemu/osdep.h\"",
        f"#include \"{pfx}_{snake}.h\"",
        "#include \"hw/qdev-properties.h\"",
        "#include \"qemu/log.h\"",
        "#include \"migration/vmstate.h\"",
        "",
    ]

    # IRQ update function
    n_irq = 0
    if peripheral.interrupt_model:
        n_irq = len(peripheral.interrupt_model.lines)
    register_names = {reg.name for reg in peripheral.register_block.registers}

    lines.append(f"static void {pfx}_{snake}_update_irq({type_name} *s)")
    lines.append("{")
    if peripheral.interrupt_model and peripheral.interrupt_model.lines:
        for i, irq_line in enumerate(peripheral.interrupt_model.lines):
            if irq_line.flags:
                conditions = []
                for flag in irq_line.flags:
                    if not flag.register_name or flag.register_name not in register_names:
                        continue
                    sr = flag.register_name.lower()
                    if flag.enable_register and flag.enable_register in register_names:
                        er = flag.enable_register.lower()
                        conditions.append(
                            f"(s->{sr} & (1U << {flag.bit_offset})) && "
                            f"(s->{er} & (1U << {flag.enable_bit_offset}))"
                        )
                    else:
                        conditions.append(f"(s->{sr} & (1U << {flag.bit_offset}))")
                if conditions:
                    cond_str = " ||\n            ".join(conditions)
                    lines.append(f"    int level_{i} = ({cond_str}) ? 1 : 0;")
                    lines.append(f"    qemu_set_irq(s->irq[{i}], level_{i});")
                else:
                    lines.append(f"    qemu_set_irq(s->irq[{i}], 0);")
    lines.append("}")
    lines.append("")

    # Read function
    lines.append(f"static uint64_t {pfx}_{snake}_read(void *opaque,")
    lines.append("    hwaddr offset, unsigned size)")
    lines.append("{")
    lines.append(f"    {type_name} *s = {pfx_upper}_{upper}(opaque);")
    lines.append("")
    lines.append(_generate_reg_read(peripheral, pfx))
    lines.append("}")
    lines.append("")

    # Write function
    lines.append(f"static void {pfx}_{snake}_write(void *opaque,")
    lines.append("    hwaddr offset, uint64_t value, unsigned size)")
    lines.append("{")
    lines.append(f"    {type_name} *s = {pfx_upper}_{upper}(opaque);")
    lines.append("")
    lines.append(_generate_reg_write(peripheral, pfx))
    lines.append("}")
    lines.append("")

    # MemoryRegionOps
    lines.append(f"static const MemoryRegionOps {pfx}_{snake}_ops = {{")
    lines.append(f"    .read = {pfx}_{snake}_read,")
    lines.append(f"    .write = {pfx}_{snake}_write,")
    lines.append("    .endianness = DEVICE_LITTLE_ENDIAN,")
    lines.append("    .impl.min_access_size = 4,")
    lines.append("    .impl.max_access_size = 4,")
    lines.append("};")
    lines.append("")

    # Reset function
    lines.append(f"static void {pfx}_{snake}_reset(DeviceState *dev)")
    lines.append("{")
    lines.append(f"    {type_name} *s = {pfx_upper}_{upper}(dev);")
    lines.append("")
    for reg in peripheral.register_block.registers:
        lines.append(f"    s->{reg.name.lower()} = 0x{reg.reset_value:08X}U;")
    if peripheral.state_machines:
        for sm in peripheral.state_machines:
            lines.append(f"    s->{_snake(sm.name)}_state = 0;")
    lines.append("")
    lines.append(f"    {pfx}_{snake}_update_irq(s);")
    lines.append("}")
    lines.append("")

    # Init function
    lines.append(f"static void {pfx}_{snake}_init(Object *obj)")
    lines.append("{")
    lines.append(f"    {type_name} *s = {pfx_upper}_{upper}(obj);")
    lines.append("    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);")
    lines.append("")
    lines.append(f"    memory_region_init_io(&s->mmio, obj, &{pfx}_{snake}_ops, s,")
    addr_size = peripheral.address_size or (
        max((r.offset for r in peripheral.register_block.registers), default=0) + 4
    )
    lines.append(f"        TYPE_{pfx_upper}_{upper}, 0x{addr_size:X});")
    lines.append("    sysbus_init_mmio(sbd, &s->mmio);")
    lines.append("")
    if n_irq:
        for i in range(n_irq):
            lines.append(f"    sysbus_init_irq(sbd, &s->irq[{i}]);")
    lines.append("}")
    lines.append("")

    # VMState for migration
    lines.append(f"static const VMStateDescription vmstate_{pfx}_{snake} = {{")
    lines.append(f"    .name = TYPE_{pfx_upper}_{upper},")
    lines.append("    .version_id = 1,")
    lines.append("    .minimum_version_id = 1,")
    lines.append("    .fields = (VMStateField[]) {")
    for reg in peripheral.register_block.registers:
        lines.append(f"        VMSTATE_UINT32({reg.name.lower()}, {type_name}),")
    lines.append("        VMSTATE_END_OF_LIST()")
    lines.append("    },")
    lines.append("};")
    lines.append("")

    # Class init
    lines.append(f"static void {pfx}_{snake}_class_init(ObjectClass *klass, void *data)")
    lines.append("{")
    lines.append("    DeviceClass *dc = DEVICE_CLASS(klass);")
    lines.append("")
    lines.append(f"    device_class_set_legacy_reset(dc, {pfx}_{snake}_reset);")
    lines.append(f"    dc->vmsd = &vmstate_{pfx}_{snake};")
    lines.append("    dc->user_creatable = true;")
    lines.append("}")
    lines.append("")

    # TypeInfo
    lines.append(f"static const TypeInfo {pfx}_{snake}_info = {{")
    lines.append(f"    .name          = TYPE_{pfx_upper}_{upper},")
    lines.append("    .parent        = TYPE_SYS_BUS_DEVICE,")
    lines.append(f"    .instance_size = sizeof({type_name}),")
    lines.append(f"    .instance_init = {pfx}_{snake}_init,")
    lines.append(f"    .class_init    = {pfx}_{snake}_class_init,")
    lines.append("};")
    lines.append("")

    # Type registration
    lines.append(f"static void {pfx}_{snake}_register_types(void)")
    lines.append("{")
    lines.append(f"    type_register_static(&{pfx}_{snake}_info);")
    lines.append("}")
    lines.append("")
    lines.append(f"type_init({pfx}_{snake}_register_types)")

    return "\n".join(lines)


def _generate_meson_build(peripheral: Peripheral) -> str:
    """Generate meson.build snippet for latest upstream QEMU in-tree integration."""
    snake = _snake(peripheral.name)
    upper = _upper(peripheral.name)
    pfx = _device_prefix(peripheral)
    pfx_upper = pfx.upper()
    return (
        f"# AutoEmu: {pfx_upper} {peripheral.name} peripheral for QEMU {QEMU_TARGET_VERSION}\n"
        f"# Add to hw/arm/meson.build or hw/misc/meson.build:\n"
        f"#   system_ss.add(when: 'CONFIG_{pfx_upper}_{upper}', if_true: files('{pfx}_{snake}.c'))\n"
        f"#\n"
        f"# Add to hw/arm/Kconfig:\n"
        f"#   config {pfx_upper}_{upper}\n"
        f"#       bool\n"
        f"\n"
        f"system_ss.add(when: 'CONFIG_{pfx_upper}_{upper}', if_true: files('{pfx}_{snake}.c'))\n"
    )


def _generate_qtest(peripheral: Peripheral) -> str:
    """Generate QTest test for latest upstream QEMU validation."""
    snake = _snake(peripheral.name)
    upper = _upper(peripheral.name)
    pfx = _device_prefix(peripheral)
    pfx_upper = pfx.upper()
    base_addr = peripheral.base_address

    lines = [
        "/*",
        f" * QTest for {pfx_upper} {peripheral.name} peripheral model",
        " *",
        f" * Auto-generated by AutoEmu (target: QEMU {QEMU_TARGET_VERSION})",
        " */",
        "",
        "#include \"qemu/osdep.h\"",
        "#include \"libqtest.h\"",
        "",
        f"#define {upper}_BASE  0x{base_addr:08X}ULL",
        "",
    ]

    # Register offset defines (duplicated for self-contained test)
    for reg in peripheral.register_block.registers:
        lines.append(f"#define {upper}_{reg.name}_OFFSET  0x{reg.offset:03X}")
    lines.append("")

    # Helper macros
    lines.append(f"#define {upper}_REG(offset)  ({upper}_BASE + (offset))")
    lines.append("")

    # Test: reset values
    lines.append(f"static void test_{snake}_reset(void)")
    lines.append("{")
    lines.append(f'    QTestState *s = qtest_init("-machine virt -device {pfx}-{snake}");')
    lines.append("")
    for reg in peripheral.register_block.registers:
        if reg.access.value != "WO":
            lines.append(
                f"    g_assert_cmphex(qtest_readl(s, {upper}_REG({upper}_{reg.name}_OFFSET)), "
                f"==, 0x{reg.reset_value:08X}U);"
            )
    lines.append("")
    lines.append("    qtest_quit(s);")
    lines.append("}")
    lines.append("")

    # Test: register write-read
    rw_regs = [r for r in peripheral.register_block.registers
               if r.access.value in ("RW",) and not any(
                   f.access.value in ("W1C", "W1S", "RO", "RSVD") for f in r.fields)]
    if rw_regs:
        reg = rw_regs[0]
        lines.append(f"static void test_{snake}_write_read(void)")
        lines.append("{")
        lines.append(f'    QTestState *s = qtest_init("-machine virt -device {pfx}-{snake}");')
        lines.append("")
        lines.append(f"    qtest_writel(s, {upper}_REG({upper}_{reg.name}_OFFSET), 0xDEADBEEFU);")
        lines.append(f"    g_assert_cmphex(qtest_readl(s, {upper}_REG({upper}_{reg.name}_OFFSET)), "
                     f"==, 0xDEADBEEFU);")
        lines.append("")
        lines.append("    qtest_quit(s);")
        lines.append("}")
        lines.append("")

    # Test: W1C behavior
    w1c_regs = [r for r in peripheral.register_block.registers
                if any(f.access.value == "W1C" for f in r.fields)]
    if w1c_regs:
        reg = w1c_regs[0]
        w1c_fields = [f for f in reg.fields if f.access.value == "W1C"]
        if w1c_fields:
            f = w1c_fields[0]
            lines.append(f"static void test_{snake}_w1c(void)")
            lines.append("{")
            lines.append(f'    QTestState *s = qtest_init("-machine virt -device {pfx}-{snake}");')
            lines.append("")
            lines.append("    /* Read status register and write 1 to clear a flag */")
            lines.append(f"    uint32_t val = qtest_readl(s, "
                         f"{upper}_REG({upper}_{reg.name}_OFFSET));")
            lines.append(f"    qtest_writel(s, {upper}_REG({upper}_{reg.name}_OFFSET), "
                         f"val | (1U << {f.bit_offset}));")
            lines.append(f"    val = qtest_readl(s, "
                         f"{upper}_REG({upper}_{reg.name}_OFFSET));")
            lines.append(f"    g_assert_cmpuint(val & (1U << {f.bit_offset}), ==, 0);")
            lines.append("")
            lines.append("    qtest_quit(s);")
            lines.append("}")
            lines.append("")

    # Test: read-only protection
    ro_regs = [r for r in peripheral.register_block.registers
               if r.access.value == "RO"]
    if ro_regs:
        reg = ro_regs[0]
        lines.append(f"static void test_{snake}_readonly(void)")
        lines.append("{")
        lines.append(f'    QTestState *s = qtest_init("-machine virt -device {pfx}-{snake}");')
        lines.append("")
        lines.append(f"    uint32_t before = qtest_readl(s, "
                     f"{upper}_REG({upper}_{reg.name}_OFFSET));")
        lines.append(f"    qtest_writel(s, {upper}_REG({upper}_{reg.name}_OFFSET), "
                     f"0xFFFFFFFFU);")
        lines.append(f"    uint32_t after = qtest_readl(s, "
                     f"{upper}_REG({upper}_{reg.name}_OFFSET));")
        lines.append("    g_assert_cmphex(before, ==, after);")
        lines.append("")
        lines.append("    qtest_quit(s);")
        lines.append("}")
        lines.append("")

    # Main with GTest registration
    lines.append("int main(int argc, char **argv)")
    lines.append("{")
    lines.append("    g_test_init(&argc, &argv, NULL);")
    lines.append("")
    lines.append(f"    qtest_add_func(\"/{pfx}/{snake}/reset\", test_{snake}_reset);")
    if rw_regs:
        lines.append(f"    qtest_add_func(\"/{pfx}/{snake}/write_read\", test_{snake}_write_read);")
    if w1c_regs:
        lines.append(f"    qtest_add_func(\"/{pfx}/{snake}/w1c\", test_{snake}_w1c);")
    if ro_regs:
        lines.append(f"    qtest_add_func(\"/{pfx}/{snake}/readonly\", test_{snake}_readonly);")
    lines.append("")
    lines.append("    return g_test_run();")
    lines.append("}")

    return "\n".join(lines)


def generate_peripheral_code(
    peripheral: Peripheral,
    output_dir: str | Path,
) -> list[str]:
    """Generate latest-upstream-QEMU peripheral model files.

    Returns list of generated file paths.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    snake = _snake(peripheral.name)
    pfx = _device_prefix(peripheral)
    files: list[str] = []

    # Header
    header_path = output_dir / f"{pfx}_{snake}.h"
    header_path.write_text(_generate_header(peripheral), encoding="utf-8")
    files.append(str(header_path))

    # Source
    source_path = output_dir / f"{pfx}_{snake}.c"
    source_path.write_text(_generate_source(peripheral), encoding="utf-8")
    files.append(str(source_path))

    # Meson build snippet
    meson_path = output_dir / "meson.build"
    meson_path.write_text(_generate_meson_build(peripheral), encoding="utf-8")
    files.append(str(meson_path))

    # QTest test
    qtest_path = output_dir / f"qtest_{pfx}_{snake}.c"
    qtest_path.write_text(_generate_qtest(peripheral), encoding="utf-8")
    files.append(str(qtest_path))

    # Model JSON (for reference)
    json_path = output_dir / f"{pfx}_{snake}_model.json"
    json_path.write_text(peripheral.model_dump_json(indent=2), encoding="utf-8")
    files.append(str(json_path))

    return files
