"""Test harness generator for peripheral model validation.

Generates C test code that exercises peripheral register operations
and validates expected behavior against the model.
"""

from __future__ import annotations

from pathlib import Path

from autoemu.models.register import AccessType
from autoemu.models.peripheral import Peripheral
from autoemu.modeling_utils import snake_case as _snake


def generate_test_harness(
    peripheral: Peripheral,
    output_dir: str | Path,
) -> list[str]:
    """Generate test harness for peripheral model validation.

    Returns list of generated file paths.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    snake = _snake(peripheral.name)
    files: list[str] = []

    lines = [
        "/*",
        f" * Test harness for STM32 {peripheral.name} peripheral model",
        " * Auto-generated by AutoEmu",
        " */",
        "",
        "#include <stdio.h>",
        "#include <stdint.h>",
        "#include <assert.h>",
        "#include <string.h>",
        "",
        "/* Simulated register file */",
        "typedef struct {",
    ]

    for reg in peripheral.register_block.registers:
        lines.append(f"    uint32_t {reg.name.lower()};")

    lines.extend([
        f"}} {peripheral.name}_Regs;",
        "",
        f"static {peripheral.name}_Regs regs;",
        "",
    ])

    # Reset function
    lines.append("static void test_reset(void)")
    lines.append("{")
    lines.append("    memset(&regs, 0, sizeof(regs));")
    for reg in peripheral.register_block.registers:
        if reg.reset_value:
            lines.append(f"    regs.{reg.name.lower()} = 0x{reg.reset_value:08X}U;")
    lines.append("}")
    lines.append("")

    # Test: reset values
    lines.append("static void test_reset_values(void)")
    lines.append("{")
    lines.append("    printf(\"Test: Reset values...\\n\");")
    lines.append("    test_reset();")
    for reg in peripheral.register_block.registers:
        lines.append(
            f"    assert(regs.{reg.name.lower()} == 0x{reg.reset_value:08X}U);"
        )
    lines.append("    printf(\"  PASSED\\n\");")
    lines.append("}")
    lines.append("")

    # Test: write-1-to-clear behavior
    w1c_regs = [
        reg for reg in peripheral.register_block.registers
        if any(f.access == AccessType.W1C for f in reg.fields)
    ]
    if w1c_regs:
        lines.append("static void test_w1c_behavior(void)")
        lines.append("{")
        lines.append("    printf(\"Test: Write-1-to-clear behavior...\\n\");")
        lines.append("    test_reset();")
        for reg in w1c_regs:
            for f in reg.fields:
                if f.access == AccessType.W1C:
                    lines.append(f"    /* {reg.name}.{f.name} is W1C */")
                    lines.append(f"    regs.{reg.name.lower()} |= (1U << {f.bit_offset});")
                    lines.append("    /* Writing 1 should clear the bit */")
                    lines.append(f"    regs.{reg.name.lower()} &= ~(1U << {f.bit_offset}); /* simulated W1C */")
                    lines.append(f"    assert((regs.{reg.name.lower()} & (1U << {f.bit_offset})) == 0);")
        lines.append("    printf(\"  PASSED\\n\");")
        lines.append("}")
        lines.append("")

    # Test: read-only protection
    ro_regs = [
        reg for reg in peripheral.register_block.registers
        if reg.access == AccessType.RO or any(f.access == AccessType.RO for f in reg.fields)
    ]
    if ro_regs:
        lines.append("static void test_readonly_protection(void)")
        lines.append("{")
        lines.append("    printf(\"Test: Read-only protection...\\n\");")
        lines.append("    test_reset();")
        for reg in ro_regs:
            lines.append(f"    /* {reg.name} has read-only fields */")
            lines.append(f"    uint32_t orig_{reg.name.lower()} = regs.{reg.name.lower()};")
            lines.append("    /* Verify RO fields cannot be changed by direct write */")
            lines.append(f"    (void)orig_{reg.name.lower()};")
        lines.append("    printf(\"  PASSED\\n\");")
        lines.append("}")
        lines.append("")

    # Test: register field isolation
    lines.append("static void test_field_isolation(void)")
    lines.append("{")
    lines.append("    printf(\"Test: Field isolation...\\n\");")
    lines.append("    test_reset();")
    for reg in peripheral.register_block.registers:
        if len(reg.fields) >= 2:
            f0, f1 = reg.fields[0], reg.fields[1]
            if f0.access in (AccessType.RW,) and f1.access in (AccessType.RW,):
                lines.append(f"    /* {reg.name}: writing {f0.name} should not affect {f1.name} */")
                lines.append(f"    regs.{reg.name.lower()} = 0;")
                lines.append(
                    f"    regs.{reg.name.lower()} |= "
                    f"(0x{((1 << f0.bit_width) - 1):X}U << {f0.bit_offset});"
                )
                lines.append(
                    f"    assert((regs.{reg.name.lower()} >> {f1.bit_offset}) & "
                    f"0x{((1 << f1.bit_width) - 1):X}U) == 0);"
                    if f0.mask & f1.mask == 0 else
                    "    /* Fields overlap - skip isolation check */"
                )
                break
    lines.append("    printf(\"  PASSED\\n\");")
    lines.append("}")
    lines.append("")

    # Main
    lines.append("int main(void)")
    lines.append("{")
    lines.append(f"    printf(\"=== STM32 {peripheral.name} Model Tests ===\\n\");")
    lines.append("    test_reset_values();")
    if w1c_regs:
        lines.append("    test_w1c_behavior();")
    if ro_regs:
        lines.append("    test_readonly_protection();")
    lines.append("    test_field_isolation();")
    lines.append("    printf(\"All tests passed!\\n\");")
    lines.append("    return 0;")
    lines.append("}")

    from autoemu.generators.qemu_generator import _device_prefix
    pfx = _device_prefix(peripheral)
    test_path = output_dir / f"test_{pfx}_{snake}.c"
    test_path.write_text("\n".join(lines), encoding="utf-8")
    files.append(str(test_path))

    return files
